#!/usr/bin/env python3
import grpc
import autogenerated.double_echo_pb2
import autogenerated.double_echo_pb2_grpc

from autogenerated.double_echo_pb2 import Msg
from autogenerated.double_echo_pb2_grpc import ServerStub

from sys import argv

def arg(default: str, pos=[0]):
  pos[0] += 1 # argument position
  return argv[pos[0]] if argv[pos[0]:] else default

MSG_TEXT = arg("test")
HOST = arg('localhost') 
PORT = arg(50051)

def main():
  with grpc.insecure_channel(f'{HOST}:{PORT}') as channel:
    stub = ServerStub(channel)
    response = stub.RemoteFunction(Msg(content=MSG_TEXT))
  print("Recieved:", response.content)

if __name__ == '__main__':
  main()