#!/usr/bin/env python3
from concurrent import futures

import grpc
import autogenerated.double_echo_pb2
import autogenerated.double_echo_pb2_grpc

from autogenerated.double_echo_pb2 import Msg
from autogenerated.double_echo_pb2_grpc import Server, add_ServerServicer_to_server

MAX_WORKERS = 4

class DoubleEchoServer(Server):
  def RemoteFunction(self, request, _):
    return Msg(content=2*request.content)

def main():
  server_service = grpc.server(futures.ThreadPoolExecutor(MAX_WORKERS))
  add_ServerServicer_to_server(DoubleEchoServer(), server_service)
  server_service.add_insecure_port('[::]:50051')
  server_service.start()
  server_service.wait_for_termination()

if __name__ == '__main__':
  main()